version: '3'
services:
  planimation_server:
    build:
      context: ${BACKEND_SOURCE}
      dockerfile: ../docker/release/Dockerfile
    image: rakeshchoyal92/planimation-backend:latest
    restart: always
    environment:
      DEBUG: "true"
    volumes:
      - ${BACKEND_SOURCE}:/code
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
